import { INTERESTED, DEDICATED, TOO_MUCH } from './utils';

export default (): Array<{
  age: number;
  climbing: number;
  music: number;
  running: number;
  poker: number;
  work: number;
}> => {
  return [
    {
      age: 3,
      climbing: 0,
      music: 0,
      running: 0,
      poker: 0,
      work: 0,
    },
    {
      age: 6,
      climbing: 0,
      music: 0,
      running: 0,
      poker: 0,
      work: 0,
    },
    {
      age: 7,
      climbing: 0,
      music: INTERESTED / 2,
      running: 0,
      poker: 0,
      work: 0,
    },
    {
      age: 8,
      climbing: 0,
      music: INTERESTED,
      running: 0,
      poker: 0,
      work: 0,
    },
    {
      age: 9,
      climbing: INTERESTED - 10,
      music: INTERESTED,
      running: 0,
      poker: 0,
      work: 0,
    },
    {
      age: 10,
      climbing: 0,
      music: INTERESTED,
      running: INTERESTED - 15,
      poker: 0,
      work: 0,
    },
    {
      age: 12,
      climbing: 0,
      music: INTERESTED,
      running: INTERESTED - 15,
      poker: 0,
      work: 0,
    },
    {
      age: 15,
      climbing: 0,
      music: DEDICATED - 10,
      running: 0,
      poker: 0,
      work: 0,
    },
    {
      age: 16,
      climbing: 0,
      music: DEDICATED - 10,
      running: 0,
      poker: 0,
      work: 20,
    },
    {
      age: 17.5,
      climbing: 0,
      music: DEDICATED - 10,
      running: 0,
      poker: 0,
      work: 0,
    },
    {
      age: 18,
      climbing: (DEDICATED + 10) * 0.33,
      music: (DEDICATED - 10) * 0.67,
      running: 0,
      poker: INTERESTED / 2,
      work: 0,
    },
    {
      age: 18.5,
      climbing: (DEDICATED + 10) * 0.67,
      music: (DEDICATED - 10) * 0.33,
      running: 0,
      poker: INTERESTED,
      work: 0,
    },
    {
      age: 19,
      climbing: DEDICATED + 10,
      music: 0,
      running: 0,
      poker: INTERESTED,
      work: 80,
    },
    {
      age: 20,
      climbing: TOO_MUCH,
      music: 0,
      running: 0,
      poker: 0,
      work: 90,
    },
    {
      age: 21,
      climbing: TOO_MUCH,
      music: 0,
      running: 0,
      poker: 0,
      work: 70,
    },
    {
      age: 24,
      climbing: TOO_MUCH,
      music: 0,
      running: 0,
      poker: 0,
      work: 70,
    },
    {
      age: 25.5,
      climbing: TOO_MUCH,
      music: 0,
      running: INTERESTED / 2,
      poker: 0,
      work: 70,
    },
    {
      age: 27,
      climbing: DEDICATED,
      music: 0,
      running: INTERESTED,
      poker: 0,
      work: 70,
    },
    {
      age: 28,
      climbing: DEDICATED,
      music: 0,
      running: INTERESTED,
      poker: 0,
      work: 70,
    },
    {
      age: 29,
      climbing: DEDICATED,
      music: 0,
      running: INTERESTED,
      poker: (INTERESTED + 10) / 2,
      work: 70,
    },
    {
      age: 30,
      climbing: DEDICATED,
      music: 0,
      running: INTERESTED,
      poker: INTERESTED + 10,
      work: 70,
    },
  ];
};
