name: Check Code

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install
        run: npm install
      - name: Typescript Validation
        run: npm run types
